apiVersion: v1
kind: Secret
metadata:
   name: wellness-connect-api-secrets
   namespace: ${NAMESPACE}
   labels:
      app: wellness-connect-api
type: Opaque
stringData:
   database-url: '${DATABASE_URL}'
